/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_carlosfortin_11911015;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Fortin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        ab.leerArchivo();
        actualizarTablaBuses();
        ae.leerArchivo();
        actualizarTablaEstudiantes();
        ap.leerArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregarBus = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sp_numbus = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        tf_placa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sp_velocidad = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jb_color = new javax.swing.JButton();
        jd_agregarEst = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nomEst = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        ff_noCuenta = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_paradas = new javax.swing.JComboBox<>();
        jb_agrEstud = new javax.swing.JButton();
        jd_agregarParada = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_nomPar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sp_distancia = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        tf_angulo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jd_simulacion = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_simulacion = new javax.swing.JTable();
        pb_tiempo = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_buses = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_estudiantes = new javax.swing.JTable();
        jb_subirEstudiante = new javax.swing.JButton();
        jb_simular = new javax.swing.JButton();
        jb_agregarBus = new javax.swing.JButton();
        jb_agregarEst = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jb_vaciar = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Agregar Bus");

        jLabel3.setText("Numero");

        sp_numbus.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel4.setText("Placa");

        jLabel5.setText("Velocidad");

        sp_velocidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton1.setText("Agregar Bus");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel17.setText("Color");

        jb_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_colorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarBusLayout = new javax.swing.GroupLayout(jd_agregarBus.getContentPane());
        jd_agregarBus.getContentPane().setLayout(jd_agregarBusLayout);
        jd_agregarBusLayout.setHorizontalGroup(
            jd_agregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarBusLayout.createSequentialGroup()
                .addGroup(jd_agregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarBusLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel2))
                    .addGroup(jd_agregarBusLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(jd_agregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1)
                            .addComponent(sp_numbus, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(tf_placa)
                            .addComponent(sp_velocidad)
                            .addComponent(jb_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jd_agregarBusLayout.setVerticalGroup(
            jd_agregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarBusLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addGroup(jd_agregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sp_numbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sp_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_agregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jb_color, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(94, 94, 94))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Agregar Estudiante");

        jLabel7.setText("Nombre");

        jLabel8.setText("Edad");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel9.setText("Numero de Cuenta");

        try {
            ff_noCuenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Parada");

        jb_agrEstud.setText("Agregar Estudiante");
        jb_agrEstud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agrEstudMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarEstLayout = new javax.swing.GroupLayout(jd_agregarEst.getContentPane());
        jd_agregarEst.getContentPane().setLayout(jd_agregarEstLayout);
        jd_agregarEstLayout.setHorizontalGroup(
            jd_agregarEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarEstLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(189, 189, 189))
            .addGroup(jd_agregarEstLayout.createSequentialGroup()
                .addGroup(jd_agregarEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarEstLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jd_agregarEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregarEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nomEst)
                            .addComponent(sp_edad, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(ff_noCuenta)
                            .addComponent(cb_paradas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jd_agregarEstLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jb_agrEstud)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_agregarEstLayout.setVerticalGroup(
            jd_agregarEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarEstLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addGroup(jd_agregarEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(tf_nomEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_agregarEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_agregarEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ff_noCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_agregarEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_paradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jb_agrEstud)
                .addGap(44, 44, 44))
        );

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Agregar Parada");

        jLabel12.setText("Nombre");

        jLabel13.setText("Distancia");

        sp_distancia.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel14.setText("Angulo");

        jLabel15.setText("x π");

        jButton2.setText("Agregar Parada");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarParadaLayout = new javax.swing.GroupLayout(jd_agregarParada.getContentPane());
        jd_agregarParada.getContentPane().setLayout(jd_agregarParadaLayout);
        jd_agregarParadaLayout.setHorizontalGroup(
            jd_agregarParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarParadaLayout.createSequentialGroup()
                .addGroup(jd_agregarParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarParadaLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel11))
                    .addGroup(jd_agregarParadaLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jd_agregarParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregarParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nomPar)
                            .addComponent(sp_distancia, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addGroup(jd_agregarParadaLayout.createSequentialGroup()
                                .addComponent(tf_angulo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)))))
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarParadaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(257, 257, 257))
        );
        jd_agregarParadaLayout.setVerticalGroup(
            jd_agregarParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarParadaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(57, 57, 57)
                .addGroup(jd_agregarParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_nomPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_agregarParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sp_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_agregarParadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_angulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(68, 68, 68)
                .addComponent(jButton2)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLabel16.setText("Simulacion");

        Tabla_simulacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parada", "Tiempo", "Estudiantes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Tabla_simulacion);

        javax.swing.GroupLayout jd_simulacionLayout = new javax.swing.GroupLayout(jd_simulacion.getContentPane());
        jd_simulacion.getContentPane().setLayout(jd_simulacionLayout);
        jd_simulacionLayout.setHorizontalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_simulacionLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addComponent(pb_tiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jd_simulacionLayout.setVerticalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_simulacionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pb_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Servicio de Transporte de UNITEC");

        Tabla_buses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Placa", "Velocidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_buses);

        Tabla_estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "No. cuenta", "Parada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla_estudiantes);

        jb_subirEstudiante.setText("Subir estudiante");
        jb_subirEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_subirEstudianteMouseClicked(evt);
            }
        });

        jb_simular.setText("Empezar Simulacion");
        jb_simular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_simularMouseClicked(evt);
            }
        });

        jb_agregarBus.setText("Agregar Bus");
        jb_agregarBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarBusMouseClicked(evt);
            }
        });

        jb_agregarEst.setText("Agregar Estudiante");
        jb_agregarEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarEstMouseClicked(evt);
            }
        });

        jButton3.setText("Agregar Parada");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jb_vaciar.setText("Vaciar Bus");
        jb_vaciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_vaciarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(666, 666, 666)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_subirEstudiante)
                                .addGap(40, 40, 40)
                                .addComponent(jb_simular)
                                .addGap(50, 50, 50)
                                .addComponent(jb_vaciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_agregarBus)
                                .addGap(52, 52, 52)
                                .addComponent(jb_agregarEst)
                                .addGap(41, 41, 41)
                                .addComponent(jButton3)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_subirEstudiante)
                    .addComponent(jb_simular)
                    .addComponent(jb_agregarBus)
                    .addComponent(jb_agregarEst)
                    .addComponent(jButton3)
                    .addComponent(jb_vaciar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_agregarBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarBusMouseClicked
        jd_agregarBus.setVisible(true);
        //jd_agregarBus.setModal(true);
        jd_agregarBus.pack();
        jd_agregarBus.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_agregarBusMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String placa=tf_placa.getText();
        int num=Integer.parseInt(sp_numbus.getValue().toString());
        int vel=Integer.parseInt(sp_velocidad.getValue().toString());
        Color color=jb_color.getBackground();
        //administrarBuses ab=new administrarBuses("./buses.cafl");
        boolean x=true;
        for (Autobus b : ab.getBuses()) {
            if(b.getNumero()==num || b.getPlaca().equals(placa)){
                x=false;
                JOptionPane.showMessageDialog(jd_agregarBus, "No pueden haber 2 buses con la misma placa o numero");
                break;
            }
        }
            if(x){
                try {
                    ab.getBuses().add(new Autobus(num, placa, vel,color));
                    ab.escribirArchivo();
                    actualizarTablaBuses();
                } catch (IOException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            tf_placa.setText("");
            sp_numbus.setValue(0);
            sp_velocidad.setValue(0);
            jb_color.setBackground(null);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_agrEstudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agrEstudMouseClicked
        String nombre=tf_nomEst.getText();
        int edad=Integer.parseInt(sp_edad.getValue().toString());
        int cuenta=Integer.parseInt(ff_noCuenta.getText());
        DefaultComboBoxModel mod=(DefaultComboBoxModel)cb_paradas.getModel();
        int pos=cb_paradas.getSelectedIndex();
        Parada parada=(Parada)mod.getElementAt(pos);
        boolean x=true;
        for (Estudiante e : ae.getEstudiantes()) {
            if(e.getNo_cuenta()==cuenta){
                x=false;
                JOptionPane.showMessageDialog(jd_agregarEst, "No pueden haber 2 estudiantes con el mismo numero de cuenta");
                break;
            }
        }
        if(x){
            try {
                ae.getEstudiantes().add(new Estudiante(nombre, edad, cuenta, parada));
                ae.escribirArchivo();
                actualizarTablaEstudiantes();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tf_nomEst.setText("");
        sp_edad.setValue(0);
        ff_noCuenta.setText("");
        cb_paradas.setSelectedIndex(-1);
    }//GEN-LAST:event_jb_agrEstudMouseClicked

    private void jb_agregarEstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarEstMouseClicked
        jd_agregarEst.setVisible(true);
        //jd_agregarEst.setModal(true);
        jd_agregarEst.pack();
        jd_agregarEst.setLocationRelativeTo(this);
        actualizarComboBoxParadas();
    }//GEN-LAST:event_jb_agregarEstMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jd_agregarParada.setVisible(true);
        jd_agregarParada.pack();
        jd_agregarParada.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String nombre=tf_nomPar.getText();
        int distancia=Integer.parseInt(sp_distancia.getValue().toString());
        String[] tokens=tf_angulo.getText().split("/");
        int num=Integer.parseInt(tokens[0]);
        int den=Integer.parseInt(tokens[1]);
        double angulo=((num*Math.PI)/den)*(180/Math.PI);
        System.out.println(angulo);
        boolean x=true;
        for (Parada p : ap.getParadas()) {
            if(p.getNombre().equals(nombre)){
                x=false;
                JOptionPane.showMessageDialog(jd_agregarParada, "No pueden haber 2 paradas con el mismo nombre");
            }
        }
        if(x){
            try {
                ap.getParadas().add(new Parada(nombre, distancia, angulo));
                ap.escribirArchivo();
                actualizarComboBoxParadas();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tf_nomPar.setText("");
        sp_distancia.setValue(0);
        tf_angulo.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_subirEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_subirEstudianteMouseClicked
        if(Tabla_buses.getSelectedRow()>=0){
            if(Tabla_estudiantes.getSelectedRow()>=0){
                Estudiante t=null;
                Autobus temp=null;
                String est=Tabla_estudiantes.getValueAt(Tabla_estudiantes.getSelectedRow(), 0).toString();
                String bus=Tabla_buses.getValueAt(Tabla_buses.getSelectedRow(), 1).toString();
                for (Estudiante e : ae.getEstudiantes()) {
                    if(e.getNombre().equals(est)){
                        t=e;
                        break;
                    }
                }
                for (Autobus buse : ab.getBuses()) {
                    if(buse.getPlaca().equals(bus)){
                        temp=buse;
                        break;
                    }
                }
                temp.getEstudiantes().add(t);
                System.out.println(temp.getEstudiantes());
            }else{
                JOptionPane.showMessageDialog(this, "Debe tener un alumno seleccionado para poder subirlo a un bus");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe tener un bus seleccionado para poder subir a un alumno");
        }
 
    }//GEN-LAST:event_jb_subirEstudianteMouseClicked

    private void jb_simularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_simularMouseClicked
        if(Tabla_buses.getSelectedRow()>=0){
            Autobus sim=null;
            String t=Tabla_buses.getValueAt(Tabla_buses.getSelectedRow(), 1).toString();
            for (Autobus buse : ab.getBuses()) {
                if(buse.getPlaca().equals(t)){
                    sim=buse;
                    break;
                }
            }
            if(sim.getEstudiantes().isEmpty())
                JOptionPane.showMessageDialog(this, "No se puede simular con un bus vacio");
            else{
                jd_simulacion.setVisible(true);
                jd_simulacion.pack();
                jd_simulacion.setLocationRelativeTo(this);
                as=new administrarSimulacion(pb_tiempo, sim, Tabla_simulacion);
                as.start();
            }
        }
    }//GEN-LAST:event_jb_simularMouseClicked

    private void jb_vaciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_vaciarMouseClicked
        if(Tabla_buses.getSelectedRow()>=0){
            Autobus temp=null;
            String bus=Tabla_buses.getValueAt(Tabla_buses.getSelectedRow(), 1).toString();
            for (Autobus buse : ab.getBuses()) {
                    if(buse.getPlaca().equals(bus)){
                        temp=buse;
                        break;
                    }
            }
            temp.setEstudiantes(new ArrayList());
        }
    }//GEN-LAST:event_jb_vaciarMouseClicked

    private void jb_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_colorMouseClicked
        jb_color.setBackground(JColorChooser.showDialog(jd_agregarBus, "Elija un color", Color.yellow));
    }//GEN-LAST:event_jb_colorMouseClicked
    
    
    public void actualizarTablaBuses(){
        Tabla_buses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Placa", "Velocidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        //administrarBuses ab=new administrarBuses("./buses.cafl");
        DefaultTableModel m=(DefaultTableModel)Tabla_buses.getModel();
        if(ab.getBuses().isEmpty()){
            
        }else{
            for (Autobus b : ab.getBuses()) {
                Object[] info={b.getNumero(),b.getPlaca(),Integer.toString(b.getVelocidad())+"km/h"};
                m.addRow(info);
            }
            Tabla_buses.setModel(m);
        }
    }
    
    public void actualizarTablaEstudiantes(){
        Tabla_estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "No. cuenta", "Parada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        //administrarEstudiantes ae=new administrarEstudiantes("./estudiantes.cafl");
        DefaultTableModel m=(DefaultTableModel)Tabla_estudiantes.getModel();
        if(ae.getEstudiantes().isEmpty()){
            
        }else{
            for (Estudiante e : ae.getEstudiantes()) {
                Object[] info={e.getNombre(),e.getNo_cuenta(),e.getParada().getNombre()};
                m.addRow(info);
            }
            Tabla_estudiantes.setModel(m);
        }
    }
    
    public void actualizarComboBoxParadas(){
        DefaultComboBoxModel m=new DefaultComboBoxModel(ap.getParadas().toArray());
        cb_paradas.setModel(m);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_buses;
    private javax.swing.JTable Tabla_estudiantes;
    private javax.swing.JTable Tabla_simulacion;
    private javax.swing.JComboBox<String> cb_paradas;
    private javax.swing.JFormattedTextField ff_noCuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_agrEstud;
    private javax.swing.JButton jb_agregarBus;
    private javax.swing.JButton jb_agregarEst;
    private javax.swing.JButton jb_color;
    private javax.swing.JButton jb_simular;
    private javax.swing.JButton jb_subirEstudiante;
    private javax.swing.JButton jb_vaciar;
    private javax.swing.JDialog jd_agregarBus;
    private javax.swing.JDialog jd_agregarEst;
    private javax.swing.JDialog jd_agregarParada;
    private javax.swing.JDialog jd_simulacion;
    private javax.swing.JProgressBar pb_tiempo;
    private javax.swing.JSpinner sp_distancia;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_numbus;
    private javax.swing.JSpinner sp_velocidad;
    private javax.swing.JTextField tf_angulo;
    private javax.swing.JTextField tf_nomEst;
    private javax.swing.JTextField tf_nomPar;
    private javax.swing.JTextField tf_placa;
    // End of variables declaration//GEN-END:variables
    administrarBuses ab=new administrarBuses("./buses.cafl");
    administrarEstudiantes ae=new administrarEstudiantes("./estudiantes.cafl");
    administrarParadas ap=new administrarParadas("./paradas.cafl");
    administrarSimulacion as;
}
